# Generated by Django 5.2.12 on 2026-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0004_monthly_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('DDR', 'DDR (Day Delegate Rate)'), ('Reception', 'Reception'), ('Dinner', 'Dinner'), ('Lunch', 'Lunch'), ('Canapes', 'Canapés'), ('Buffet', 'Buffet'), ('Breakfast', 'Breakfast'), ('Tasting', 'Menu Tasting'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlyhoursledger',
            name='holiday_minutes',
            field=models.IntegerField(default=0, help_text='Minutes from H days counted at 8 h each'),
        ),
        migrations.AlterField(
            model_name='monthlyhoursledger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monthlyhoursledger',
            name='month',
            field=models.CharField(help_text='YYYY-MM', max_length=7),
        ),
        migrations.AlterField(
            model_name='monthlyhoursledger',
            name='net_minutes',
            field=models.IntegerField(default=0, help_text='Actual net paid minutes from working shifts (breaks deducted)'),
        ),
        migrations.AlterField(
            model_name='monthlyhoursledger',
            name='status',
            field=models.CharField(choices=[('ok', 'On target'), ('under', 'Under hours'), ('over', 'Over hours')], default='ok', max_length=10),
        ),
        migrations.AlterField(
            model_name='monthlyhoursledger',
            name='target_minutes',
            field=models.IntegerField(default=10410, help_text='Monthly target in minutes — 173.5 h × 60 for full-time'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contracted_hours_pw',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Contracted hours per week', max_digits=5),
        ),
        migrations.AlterField(
            model_name='staff',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffingrule',
            name='event_type',
            field=models.CharField(help_text='e.g. DDR, Reception, Dinner', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffingrule',
            name='shift_suggestion',
            field=models.CharField(default='0800-1630', max_length=30),
        ),
    ]
